version: '2'
services:
  web:
    build: .
    command: php -S 0.0.0.0:8000 -t /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  mariadb:
    image: mariadb
    environment:
    - MYSQL_ROOT_PASSWORD=password
    ports:
      - "32785:3306"