version: '2'
services:
  web:
    build: .
    working_dir: /app
    links:
      - mariadb
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  mariadb:
    image: mariadb
    environment:
    - MYSQL_ROOT_PASSWORD=password
    ports:
      - "32785:3306"